# Generated by Django 4.0.5 on 2022-06-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelForAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SrNo', models.CharField(max_length=25)),
                ('NametoAdd', models.CharField(max_length=250)),
                ('phonetoadd', models.CharField(max_length=250)),
                ('addresstoadd', models.CharField(max_length=250)),
            ],
        ),
    ]
